authors: []
blacklist:
- ocs2_raisim
- ocs2_raisim_ros
- ocs2_raisim_core
- ocs2_legged_robot_raisim
- ocs2_cart_pole_raisim
- ocs2_ballbot_raisim
- ocs2_doc
- ocs2_legged_robot
- ocs2_legged_robot_ros
- ocs2_quadrotor
- ocs2_quadrotor_ros
- ocs2_centroidal_model
- ocs2_sphere_approximation
- ocs2_cartpole
- ocs2_cartpole_ros
- ocs2_double_integrator
- ocs2_double_integrator_ros
- ocs2_mobile_manipulator
- ocs2_mobile_manipulator_ros
- ocs2_ballbot
- ocs2_ballbot_ros
- ocs2_robotic_examples
- ocs2_self_collision_visualization
- robotiq_3f_gripper_articulated_gazebo_plugins
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
- -DPYTHON_EXECUTABLE=/usr/bin/python3
- -DBUILD_TESTING=OFF
- -DBUILD_PYTHON_INTERFACE=ON
- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
devel_layout: linked
devel_space: devel
extend_path: /opt/ros/noetic
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses: TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
